version: "3"
x-defaults: &defaults
  env_file:
    - .env


services:
  go-tg-bot-postgres:
    <<: *defaults
    container_name: go-tg-bot-postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ${GO_TG_BOT_DB_NAME}
      POSTGRES_USER: ${GO_TG_BOT_DB_USER}
      POSTGRES_PASSWORD: ${GO_TG_BOT_DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db/dump:/var/lib/postgresql/data
    ports:
      - "5432:5432"




