// Code generated by entc, DO NOT EDIT.

package ent

import (
	"go-tg-bot/internal/repository/ent/event"
	"go-tg-bot/internal/repository/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventMixin := schema.Event{}.Mixin()
	eventMixinFields0 := eventMixin[0].Fields()
	_ = eventMixinFields0
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescCreateAt is the schema descriptor for create_at field.
	eventDescCreateAt := eventMixinFields0[0].Descriptor()
	// event.DefaultCreateAt holds the default value on creation for the create_at field.
	event.DefaultCreateAt = eventDescCreateAt.Default.(func() time.Time)
	// eventDescUpdateAt is the schema descriptor for update_at field.
	eventDescUpdateAt := eventMixinFields0[1].Descriptor()
	// event.DefaultUpdateAt holds the default value on creation for the update_at field.
	event.DefaultUpdateAt = eventDescUpdateAt.Default.(func() time.Time)
	// event.UpdateDefaultUpdateAt holds the default value on update for the update_at field.
	event.UpdateDefaultUpdateAt = eventDescUpdateAt.UpdateDefault.(func() time.Time)
	// eventDescName is the schema descriptor for name field.
	eventDescName := eventFields[1].Descriptor()
	// event.NameValidator is a validator for the "name" field. It is called by the builders before save.
	event.NameValidator = eventDescName.Validators[0].(func(string) error)
	// eventDescDescription is the schema descriptor for description field.
	eventDescDescription := eventFields[2].Descriptor()
	// event.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	event.DescriptionValidator = eventDescDescription.Validators[0].(func(string) error)
	// eventDescLocation is the schema descriptor for location field.
	eventDescLocation := eventFields[3].Descriptor()
	// event.LocationValidator is a validator for the "location" field. It is called by the builders before save.
	event.LocationValidator = eventDescLocation.Validators[0].(func(string) error)
	// eventDescID is the schema descriptor for id field.
	eventDescID := eventFields[0].Descriptor()
	// event.DefaultID holds the default value on creation for the id field.
	event.DefaultID = eventDescID.Default.(func() uuid.UUID)
}
